version: "3"

networks:
    traefik-public:
        external: true

services:
  belief-server:
    networks:
      - traefik-public
      - default
    image: 127.0.0.1:5000/belief
    env_file:
      - .env
    build: .
    container_name: belief.aristosci.ninja-server
    deploy:
        labels:
        - "traefik.enable=true"
        #Setup Endpoints for http and https
        - "traefik.http.routers.belief-server.entrypoints=https"
        - "traefik.http.routers.belief-server.rule=Host(`belief.aristosci.ninja`)"
        - "traefik.http.routers.belief-server-http.entrypoints=http"
        - "traefik.http.routers.belief-server-http.rule=Host(`belief.aristosci.ninja`)"
        - "traefik.http.routers.belief-server-http.middlewares=belief-server-https@docker"
        - "traefik.http.middlewares.belief-server-https.redirectscheme.scheme=https"
        - "traefik.constraint-label=traefik-public"
        - traefik.http.routers.belief-server.service=belief-backend
        - "traefik.http.services.belief-backend.loadbalancer.server.port=8080"
        - "traefik.http.routers.belief-server.tls=true"
        - "traefik.http.routers.belief-server.tls.certresolver=le"


